[mypy]
python_version = 3.11
files = experiments/pysim/tier1_core, experiments/pysim/tier1_interface, experiments/pysim/tier2_runtime, experiments/pysim/tier3_jit
mypy_path = experiments/pysim/tier1_core:experiments/pysim/tier1_interface:experiments/pysim/tier2_runtime:experiments/pysim/tier3_jit
explicit_package_bases = True
namespace_packages = True
follow_imports = skip
ignore_missing_imports = True
check_untyped_defs = True
disallow_any_generics = True
no_implicit_optional = True
warn_return_any = True
warn_unused_ignores = True
show_error_codes = True
