[pytest]
testpaths = experiments/pysim/qa
addopts = --import-mode=importlib
pythonpath =
    experiments/pysim
    experiments/pysim/qa
    experiments/pysim/tier1_core
    experiments/pysim/tier1_interface
    experiments/pysim/tier2_runtime
    experiments/pysim/tier3_executer
    experiments/pysim/tier3_plugins
    experiments/pysim/tier3_platform
    docs/components/tier1_core/concepts
    docs/components/tier1_interface/concepts
    docs/components/tier2_runtime/concepts
    docs/components/tier3_executer/concepts
    docs/components/tier3_platform/concepts
