package fireball:host;

interface guest-api {
    use types.{operation-result, log-level, message};
    log: func(lvl: log-level, dict-id: u32, value: u32);
    ipc-call: func(chan: u32, data: message) -> operation-result;
}

world fireball-system {
    import types;
    import hal;
    import vsoc;
    import jit;
    import services;
    
    export guest-api;
}
