package fireball:host;

world fireball-system {
    import types;
    import hal;
    import vsoc;
    import jit;
    import services;

    export interface guest-api {
        use types.{operation-result, shm-id};
        log: func(msg: shm-id);
        ipc-call: func(chan: u32, data: shm-id) -> operation-result;
    }
}
