package fireball:host;

interface guest-api {
    use types.{operation-result, sys-log-level, ipc-message};
    log: func(lvl: sys-log-level, dict-id: u32, value: u32);
    call: func(chan: u32, data: ipc-message) -> operation-result;
}

world fireball-system {
    import types;
    import hal;
    import vsoc;
    import jit;
    import services;
    
    export guest-api;
}
