package fireball:host;

interface trap {
    /// Performs a low-level host call with raw arguments.
    /// Variants for optimization based on argument count.
    fireball-call0: func(id: u32) -> u32;
    fireball-call1: func(id: u32, a0: u32) -> u32;
    fireball-call2: func(id: u32, a0: u32, a1: u32) -> u32;
    fireball-call3: func(id: u32, a0: u32, a1: u32, a2: u32) -> u32;
    fireball-call4: func(id: u32, a0: u32, a1: u32, a2: u32, a3: u32) -> u32;
    fireball-call5: func(id: u32, a0: u32, a1: u32, a2: u32, a3: u32, a4: u32) -> u32;
    fireball-call6: func(id: u32, a0: u32, a1: u32, a2: u32, a3: u32, a4: u32, a5: u32) -> u32;
}

world syscall {
    import trap;
}
